import "./globals.css";
import { Playfair_Display, Merriweather } from "next/font/google";
import Header from "./layout/Header";

const plf = Playfair_Display({ subsets: ["latin"] });
const Merri = Merriweather({
  subsets: ["latin"],
  weight: "300",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`{plf.className} {Merri.className} `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
